version: '3'

services:
  postgres:
    image: postgres:13.2
    environment:
      POSTGRES_USER: url
      POSTGRES_PASSWORD: url
      POSTGRES_DB: url
    ports:
      - '5400:5432'
    volumes:
      - './_postgres/:/docker-entrypoint-initdb.d/'
  tinyurl:
    image: dazkh/tinyurl
    build:
      .
    depends_on:
      - postgres
    ports:
      - "8091:8091"